require 'yaml'

@config = YAML.load_file(File.expand_path('../_tasks/config.yaml', __FILE__))

# Pull rake taskes in from takes directory
task_dir = File.expand_path('../_tasks', __FILE__)

# Pull in the functional Rake tasks
Dir["#{task_dir}/**/*.rake"].each do |task_file|
    load task_file
end

# Create the stub tasks for tracking upload state and for manual deploys
Dir["./repos/courseware-lms-content/_lmscontent/*"].each do |component_directory|
  if File.exists?("#{component_directory}/metadata.json")
    #puts component_directory
    namespace :release do
      desc "Build component (#{File.basename(component_directory)}) and upload a release to <target>"
      task File.basename(component_directory).to_sym ,[:target] do  |_t, args|
        puts "invoking \`rake upload:component:#{File.basename(component_directory)}\`"
        Rake::Task['upload:component'].reenable
        Rake::Task['upload:component'].invoke(component_directory,args[:target]) 
      end
    end
  end
end

# Run interactively if user gives us no arguments
task :default => ['help']
